// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA617JP-itXngOZsUpLxFpgHiChUuVSzSo',
    appId: '1:901270565634:android:aaede3d1dd34346380c81b',
    messagingSenderId: '901270565634',
    projectId: 'rakna-3888c',
    databaseURL: 'https://rakna-3888c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rakna-3888c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhF3l9uSunxz-0XRNau97l3t9dF-g4a4',
    appId: '1:901270565634:ios:e2316b040205646280c81b',
    messagingSenderId: '901270565634',
    projectId: 'rakna-3888c',
    databaseURL: 'https://rakna-3888c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rakna-3888c.appspot.com',
    iosClientId: '901270565634-d23k7r0dh220gsk0r9i1rasc1gof7icm.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakna',
  );
}
